"""add_auto_apply

Revision ID: b8e37daa1ace
Revises: c9f2
Create Date: 2026-06-20 22:52:45.666270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8e37daa1ace'
down_revision: Union[str, Sequence[str], None] = 'c9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('total_successes', sa.Integer(), nullable=True),
    sa.Column('total_failures', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('avg_duration_seconds', sa.Float(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('last_failure', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform')
    )
    op.create_index('idx_ph_platform', 'platform_health', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_health_id'), 'platform_health', ['id'], unique=False)
    op.create_table('application_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('encrypted_cookies', sa.Text(), nullable=True),
    sa.Column('encrypted_session_tokens', sa.Text(), nullable=True),
    sa.Column('encrypted_username', sa.Text(), nullable=True),
    sa.Column('encrypted_password', sa.Text(), nullable=True),
    sa.Column('requires_password_storage', sa.Boolean(), nullable=True),
    sa.Column('session_valid_until', sa.DateTime(), nullable=True),
    sa.Column('fingerprint_profile_id', sa.String(length=255), nullable=True),
    sa.Column('proxy_id', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('consent_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform', name='uq_account_user_platform')
    )
    op.create_index('idx_aa_user_platform', 'application_accounts', ['user_id', 'platform'], unique=False)
    op.create_index(op.f('ix_application_accounts_id'), 'application_accounts', ['id'], unique=False)
    op.create_table('application_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ar_candidate', 'application_runs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_application_runs_id'), 'application_runs', ['id'], unique=False)
    op.create_table('application_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('jobs_selected', sa.Integer(), nullable=True),
    sa.Column('jobs_queued', sa.Integer(), nullable=True),
    sa.Column('jobs_skipped', sa.Integer(), nullable=True),
    sa.Column('jobs_rate_limited', sa.Integer(), nullable=True),
    sa.Column('applications_started', sa.Integer(), nullable=True),
    sa.Column('applications_submitted', sa.Integer(), nullable=True),
    sa.Column('applications_failed', sa.Integer(), nullable=True),
    sa.Column('otp_required', sa.Integer(), nullable=True),
    sa.Column('email_verifications', sa.Integer(), nullable=True),
    sa.Column('accounts_created', sa.Integer(), nullable=True),
    sa.Column('review_required', sa.Integer(), nullable=True),
    sa.Column('review_approved', sa.Integer(), nullable=True),
    sa.Column('review_rejected', sa.Integer(), nullable=True),
    sa.Column('requirements_failed', sa.Integer(), nullable=True),
    sa.Column('platform_disabled_skips', sa.Integer(), nullable=True),
    sa.Column('questions_answered', sa.Integer(), nullable=True),
    sa.Column('cover_letters_generated', sa.Integer(), nullable=True),
    sa.Column('forms_submitted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['application_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('idx_am_candidate', 'application_metrics', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_application_metrics_id'), 'application_metrics', ['id'], unique=False)
    op.create_table('application_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('apply_url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('adapter_version', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('skill_match_score', sa.Float(), nullable=True),
    sa.Column('selected_resume_id', sa.Integer(), nullable=True),
    sa.Column('approval_mode', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('consent_ref', sa.String(length=255), nullable=True),
    sa.Column('checkpoint_thread_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['application_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_resume_id'], ['candidate_resumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_at_candidate_status', 'application_tasks', ['candidate_id', 'status'], unique=False)
    op.create_index('idx_at_run', 'application_tasks', ['run_id'], unique=False)
    op.create_index(op.f('ix_application_tasks_id'), 'application_tasks', ['id'], unique=False)
    op.create_table('application_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['application_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aqa_candidate_hash', 'application_answers', ['candidate_id', 'question_hash'], unique=False)
    op.create_index(op.f('ix_application_answers_id'), 'application_answers', ['id'], unique=False)
    op.create_table('application_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['application_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['application_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aa_action', 'application_audits', ['action'], unique=False)
    op.create_index('idx_aa_run', 'application_audits', ['run_id'], unique=False)
    op.create_index('idx_aa_task', 'application_audits', ['task_id'], unique=False)
    op.create_index(op.f('ix_application_audits_id'), 'application_audits', ['id'], unique=False)
    op.create_table('application_cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['application_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('idx_acl_candidate', 'application_cover_letters', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_application_cover_letters_id'), 'application_cover_letters', ['id'], unique=False)
    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('resume_type', sa.String(length=20), nullable=True),
    sa.Column('resume_score', sa.Float(), nullable=True),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['candidate_resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['application_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('idx_ad_task', 'application_documents', ['task_id'], unique=False)
    op.create_index(op.f('ix_application_documents_id'), 'application_documents', ['id'], unique=False)
    op.create_table('application_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['application_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['application_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_al_run', 'application_logs', ['run_id'], unique=False)
    op.create_index('idx_al_task', 'application_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_application_logs_id'), 'application_logs', ['id'], unique=False)
    op.create_table('application_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['application_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ash_task', 'application_status_history', ['task_id'], unique=False)
    op.create_index(op.f('ix_application_status_history_id'), 'application_status_history', ['id'], unique=False)

    op.add_column('candidate_resumes', sa.Column('resume_type', sa.String(length=20), nullable=True))
    op.alter_column('course_analytics', 'completion_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_analytics', 'avg_watch_time',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_analytics', 'avg_quiz_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_analytics', 'certificate_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.create_index(op.f('ix_course_analytics_course_id'), 'course_analytics', ['course_id'], unique=False)
    op.alter_column('course_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course_progress', 'video_progress',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_progress', 'pdf_progress',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_progress', 'quiz_progress',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_progress', 'overall_progress',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('unique_user_course'), 'course_progress', type_='unique')
    op.create_index(op.f('ix_course_progress_id'), 'course_progress', ['id'], unique=False)
    op.drop_index(op.f('idx_interviews_status'), table_name='interviews')
    op.alter_column('job_agent_runs', 'stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('job_matches', 'reasons_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('job_pool_matches', 'reasons_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('jobs_pool', 'all_sources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('learning_events', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_learning_events_id'), 'learning_events', ['id'], unique=False)
    op.drop_index(op.f('idx_mcp_chat_session_pinned_updated'), table_name='mcp_chat_sessions')
    op.add_column('user_consents', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.add_column('user_consents', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('user_preferences', sa.Column('auto_apply_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_preferences', sa.Column('auto_apply_approval_mode', sa.String(length=20), nullable=True))
    op.add_column('user_preferences', sa.Column('auto_apply_min_score', sa.Float(), nullable=True))
    op.add_column('user_preferences', sa.Column('auto_apply_min_skill_match', sa.Float(), nullable=True))
    op.add_column('user_preferences', sa.Column('auto_apply_daily_cap', sa.Integer(), nullable=True))
    op.add_column('user_preferences', sa.Column('auto_apply_remote_only', sa.Boolean(), nullable=True))
    op.add_column('user_preferences', sa.Column('auto_apply_max_job_age_days', sa.Integer(), nullable=True))
    op.add_column('user_preferences', sa.Column('auto_apply_locations', sa.Text(), nullable=True))
    op.add_column('user_preferences', sa.Column('auto_apply_domains', sa.Text(), nullable=True))
    op.alter_column('video_analytics', 'load_time',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('video_analytics', 'buffer_duration',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.create_index(op.f('ix_video_analytics_id'), 'video_analytics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_analytics_id'), table_name='video_analytics')
    op.alter_column('video_analytics', 'buffer_duration',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('video_analytics', 'load_time',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_column('user_preferences', 'auto_apply_domains')
    op.drop_column('user_preferences', 'auto_apply_locations')
    op.drop_column('user_preferences', 'auto_apply_max_job_age_days')
    op.drop_column('user_preferences', 'auto_apply_remote_only')
    op.drop_column('user_preferences', 'auto_apply_daily_cap')
    op.drop_column('user_preferences', 'auto_apply_min_skill_match')
    op.drop_column('user_preferences', 'auto_apply_min_score')
    op.drop_column('user_preferences', 'auto_apply_approval_mode')
    op.drop_column('user_preferences', 'auto_apply_enabled')
    op.drop_column('user_consents', 'metadata_json')
    op.drop_column('user_consents', 'revoked_at')
    op.create_index(op.f('idx_mcp_chat_session_pinned_updated'), 'mcp_chat_sessions', ['is_pinned', sa.literal_column('updated_at DESC')], unique=False)
    op.drop_index(op.f('ix_learning_events_id'), table_name='learning_events')
    op.alter_column('learning_events', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs_pool', 'all_sources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('job_pool_matches', 'reasons_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('job_matches', 'reasons_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('job_agent_runs', 'stats',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_interviews_status'), 'interviews', ['status'], unique=False)
    op.drop_index(op.f('ix_course_progress_id'), table_name='course_progress')
    op.create_unique_constraint(op.f('unique_user_course'), 'course_progress', ['user_id', 'course_id'])
    op.alter_column('course_progress', 'overall_progress',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_progress', 'quiz_progress',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_progress', 'pdf_progress',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_progress', 'video_progress',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_course_analytics_course_id'), table_name='course_analytics')
    op.alter_column('course_analytics', 'certificate_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_analytics', 'avg_quiz_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_analytics', 'avg_watch_time',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('course_analytics', 'completion_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.drop_column('candidate_resumes', 'resume_type')
    op.create_index(op.f('idx_audit_logs_timestamp'), 'audit_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_applications_status'), 'applications', ['status'], unique=False)
    op.add_column('ai_mentor_usage', sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_mentor_usage', sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_mentor_usage', sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_mentor_usage', sa.Column('estimated_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_ai_mentor_studyplans_search'), 'ai_mentor_study_plans', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_ai_mentor_sessions_search'), 'ai_mentor_sessions', [sa.literal_column("to_tsvector('english'::regconfig, title::text)")], unique=False, postgresql_using='gin', postgresql_where='(is_archived = false)')
    op.create_index(op.f('idx_ai_mentor_messages_search'), 'ai_mentor_messages', [sa.literal_column("to_tsvector('english'::regconfig, message)")], unique=False, postgresql_using='gin', postgresql_where='(is_archived = false)')
    op.create_index(op.f('idx_ai_mentor_artifacts_search'), 'ai_mentor_artifacts', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin', postgresql_where='(is_archived = false)')
    op.create_table('module_quiz_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['module_quizzes.id'], name=op.f('module_quiz_attempts_quiz_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('module_quiz_attempts_pkey'))
    )
    op.create_table('user_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('courseId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('moduleId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('videoCompleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pdfCompleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('quizCompleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('writtenCompleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('interviewCompleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('moduleUnlocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('nextModuleUnlocked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_progress_pkey'))
    )
    op.create_index(op.f('idx_user_progress_user_module'), 'user_progress', ['userId', 'moduleId'], unique=False)
    op.create_index(op.f('idx_user_progress_user_course'), 'user_progress', ['userId', 'courseId'], unique=False)
    op.create_index(op.f('idx_user_progress_user'), 'user_progress', ['userId'], unique=False)
    op.create_table('readiness_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quiz_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('written_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interview_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('project_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_ready', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('readiness_scores_pkey'))
    )
    op.create_table('pdfs',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topicid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('pdfurl', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topicid'], ['topics.id'], name=op.f('pdfs_topicid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pdfs_pkey'))
    )
    op.create_index(op.f('idx_pdfs_topicid'), 'pdfs', ['topicid'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topicid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('youtubeurl', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topicid'], ['topics.id'], name=op.f('lessons_topicid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lessons_pkey'))
    )
    op.create_index(op.f('idx_lessons_topicid'), 'lessons', ['topicid'], unique=False)
    op.create_table('ai_interview_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ai_interview_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('transcript_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('knowledge_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('communication_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('eye_contact_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('body_language_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interview_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ai_interview_id'], ['ai_interviews.id'], name=op.f('ai_interview_attempts_ai_interview_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_interview_attempts_pkey'))
    )
    op.create_table('final_ai_interviews',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('courseid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('passpercentage', sa.INTEGER(), server_default=sa.text('70'), autoincrement=False, nullable=True),
    sa.Column('questions_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['courseid'], ['courses.id'], name=op.f('final_ai_interviews_courseid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('final_ai_interviews_pkey'))
    )
    op.create_table('quizzes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('moduleId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('passPercentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('questions_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('quizzes_pkey'))
    )
    op.create_index(op.f('idx_quizzes_module'), 'quizzes', ['moduleId'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('enrollments_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('enrollments_pkey'))
    )
    op.create_index(op.f('idx_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_index(op.f('idx_enrollments_course_user'), 'enrollments', ['user_id', 'course_id'], unique=False)
    op.create_table('module_quizzes',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('moduleid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('passpercentage', sa.INTEGER(), server_default=sa.text('70'), autoincrement=False, nullable=True),
    sa.Column('questions_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['moduleid'], ['modules.id'], name=op.f('module_quizzes_moduleid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('module_quizzes_pkey'))
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_attempts_pkey'))
    )
    op.create_table('topics',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('moduleid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topicno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estimatedduration', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('orderno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['moduleid'], ['modules.id'], name=op.f('topics_moduleid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('topics_pkey'))
    )
    op.create_index(op.f('idx_topics_moduleid'), 'topics', ['moduleid'], unique=False)
    op.create_index(op.f('idx_topics_module_no'), 'topics', ['moduleid', 'topicno'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('instructor', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('reviews', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('thumbnail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('totalmodules', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Published'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('courses_pkey'))
    )
    op.create_table('ai_interviews',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('moduleid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('passpercentage', sa.INTEGER(), server_default=sa.text('70'), autoincrement=False, nullable=True),
    sa.Column('questions_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['moduleid'], ['modules.id'], name=op.f('ai_interviews_moduleid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_interviews_pkey'))
    )
    op.create_table('final_ai_interview_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interview_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('transcript_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('knowledge_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('communication_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('problem_solving_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interview_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['final_ai_interviews.id'], name=op.f('final_ai_interview_attempts_interview_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('final_ai_interview_attempts_pkey'))
    )
    op.create_table('final_assessment_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['final_assessments.id'], name=op.f('final_assessment_attempts_assessment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('final_assessment_attempts_pkey'))
    )
    op.create_table('modules',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('courseid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('moduleno', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('unlockorder', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['courseid'], ['courses.id'], name=op.f('modules_courseid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('modules_pkey'))
    )
    op.create_index(op.f('idx_modules_course_unlock'), 'modules', ['courseid', 'unlockorder'], unique=False)
    op.create_table('project_submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('github_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submission_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_submissions_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_submissions_pkey'))
    )
    op.create_table('projects',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('courseid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['courseid'], ['courses.id'], name=op.f('projects_courseid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_table('written_assessments',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('moduleid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('passpercentage', sa.INTEGER(), server_default=sa.text('70'), autoincrement=False, nullable=True),
    sa.Column('questions_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['moduleid'], ['modules.id'], name=op.f('written_assessments_moduleid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('written_assessments_pkey'))
    )
    op.create_index(op.f('idx_written_assessments_module'), 'written_assessments', ['moduleid'], unique=False)
    op.create_table('final_assessments',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('courseid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('passpercentage', sa.INTEGER(), server_default=sa.text('70'), autoincrement=False, nullable=True),
    sa.Column('questions_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['courseid'], ['courses.id'], name=op.f('final_assessments_courseid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('final_assessments_pkey'))
    )
    op.create_table('topic_quizzes',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topicid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('passpercentage', sa.INTEGER(), server_default=sa.text('70'), autoincrement=False, nullable=True),
    sa.Column('questions_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topicid'], ['topics.id'], name=op.f('topic_quizzes_topicid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_quizzes_pkey'))
    )
    op.create_table('topic_quiz_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_quiz_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topic_quiz_id'], ['topic_quizzes.id'], name=op.f('topic_quiz_attempts_topic_quiz_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_quiz_attempts_pkey'))
    )
    op.create_table('written_assessment_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('written_assessment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('answers_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('grammar_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('technical_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['written_assessment_id'], ['written_assessments.id'], name=op.f('written_assessment_attempts_written_assessment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('written_assessment_attempts_pkey'))
    )
    op.create_table('topic_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('courseid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('moduleid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('topicid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('videocompleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('pdfcompleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('topicquizcompleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_progress_pkey'))
    )
    op.create_index(op.f('idx_topic_progress_user'), 'topic_progress', ['userid'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certificate_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quiz_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('written_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('project_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('interview_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('readiness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('certificate_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('earned_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('certificates_pkey'))
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey')),
    sa.UniqueConstraint('name', name=op.f('categories_name_key'))
    )
    op.create_table('module_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('courseid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('moduleid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('modulequizcompleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('writtencompleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('interviewcompleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('projectcompleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('moduleunlocked', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('nextmoduleunlocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('module_progress_pkey'))
    )
    op.create_index(op.f('idx_module_progress_user'), 'module_progress', ['userid'], unique=False)
    op.drop_index(op.f('ix_application_status_history_id'), table_name='application_status_history')
    op.drop_index('idx_ash_task', table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index(op.f('ix_application_logs_id'), table_name='application_logs')
    op.drop_index('idx_al_task', table_name='application_logs')
    op.drop_index('idx_al_run', table_name='application_logs')
    op.drop_table('application_logs')
    op.drop_index(op.f('ix_application_documents_id'), table_name='application_documents')
    op.drop_index('idx_ad_task', table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_application_cover_letters_id'), table_name='application_cover_letters')
    op.drop_index('idx_acl_candidate', table_name='application_cover_letters')
    op.drop_table('application_cover_letters')
    op.drop_index(op.f('ix_application_audits_id'), table_name='application_audits')
    op.drop_index('idx_aa_task', table_name='application_audits')
    op.drop_index('idx_aa_run', table_name='application_audits')
    op.drop_index('idx_aa_action', table_name='application_audits')
    op.drop_table('application_audits')
    op.drop_index(op.f('ix_application_answers_id'), table_name='application_answers')
    op.drop_index('idx_aqa_candidate_hash', table_name='application_answers')
    op.drop_table('application_answers')
    op.drop_index(op.f('ix_application_tasks_id'), table_name='application_tasks')
    op.drop_index('idx_at_run', table_name='application_tasks')
    op.drop_index('idx_at_candidate_status', table_name='application_tasks')
    op.drop_table('application_tasks')
    op.drop_index(op.f('ix_application_metrics_id'), table_name='application_metrics')
    op.drop_index('idx_am_candidate', table_name='application_metrics')
    op.drop_table('application_metrics')
    op.drop_index(op.f('ix_application_runs_id'), table_name='application_runs')
    op.drop_index('idx_ar_candidate', table_name='application_runs')
    op.drop_table('application_runs')
    op.drop_index(op.f('ix_application_accounts_id'), table_name='application_accounts')
    op.drop_index('idx_aa_user_platform', table_name='application_accounts')
    op.drop_table('application_accounts')
    op.drop_index(op.f('ix_platform_health_id'), table_name='platform_health')
    op.drop_index('idx_ph_platform', table_name='platform_health')
    op.drop_table('platform_health')
    # ### end Alembic commands ###
